#![doc = "Peripheral access API for RP2040 microcontrollers (generated using svd2rust v0.36.0 ( ))  

You can find an overview of the generated API [here].  

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.  

[here]: https://docs.rs/svd2rust/0.36.0/svd2rust/#peripheral-api  
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased  
[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn TIMER_IRQ_0();
    fn TIMER_IRQ_1();
    fn TIMER_IRQ_2();
    fn TIMER_IRQ_3();
    fn PWM_IRQ_WRAP();
    fn USBCTRL_IRQ();
    fn XIP_IRQ();
    fn PIO0_IRQ_0();
    fn PIO0_IRQ_1();
    fn PIO1_IRQ_0();
    fn PIO1_IRQ_1();
    fn DMA_IRQ_0();
    fn DMA_IRQ_1();
    fn IO_IRQ_BANK0();
    fn IO_IRQ_QSPI();
    fn SIO_IRQ_PROC0();
    fn SIO_IRQ_PROC1();
    fn CLOCKS_IRQ();
    fn SPI0_IRQ();
    fn SPI1_IRQ();
    fn UART0_IRQ();
    fn UART1_IRQ();
    fn ADC_IRQ_FIFO();
    fn I2C0_IRQ();
    fn I2C1_IRQ();
    fn RTC_IRQ();
    fn SW0_IRQ();
    fn SW1_IRQ();
    fn SW2_IRQ();
    fn SW3_IRQ();
    fn SW4_IRQ();
    fn SW5_IRQ();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector {
        _handler: TIMER_IRQ_0,
    },
    Vector {
        _handler: TIMER_IRQ_1,
    },
    Vector {
        _handler: TIMER_IRQ_2,
    },
    Vector {
        _handler: TIMER_IRQ_3,
    },
    Vector {
        _handler: PWM_IRQ_WRAP,
    },
    Vector {
        _handler: USBCTRL_IRQ,
    },
    Vector { _handler: XIP_IRQ },
    Vector {
        _handler: PIO0_IRQ_0,
    },
    Vector {
        _handler: PIO0_IRQ_1,
    },
    Vector {
        _handler: PIO1_IRQ_0,
    },
    Vector {
        _handler: PIO1_IRQ_1,
    },
    Vector {
        _handler: DMA_IRQ_0,
    },
    Vector {
        _handler: DMA_IRQ_1,
    },
    Vector {
        _handler: IO_IRQ_BANK0,
    },
    Vector {
        _handler: IO_IRQ_QSPI,
    },
    Vector {
        _handler: SIO_IRQ_PROC0,
    },
    Vector {
        _handler: SIO_IRQ_PROC1,
    },
    Vector {
        _handler: CLOCKS_IRQ,
    },
    Vector { _handler: SPI0_IRQ },
    Vector { _handler: SPI1_IRQ },
    Vector {
        _handler: UART0_IRQ,
    },
    Vector {
        _handler: UART1_IRQ,
    },
    Vector {
        _handler: ADC_IRQ_FIFO,
    },
    Vector { _handler: I2C0_IRQ },
    Vector { _handler: I2C1_IRQ },
    Vector { _handler: RTC_IRQ },
    Vector { _handler: SW0_IRQ },
    Vector { _handler: SW1_IRQ },
    Vector { _handler: SW2_IRQ },
    Vector { _handler: SW3_IRQ },
    Vector { _handler: SW4_IRQ },
    Vector { _handler: SW5_IRQ },
];
#[doc = r"Enumeration of all the interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - TIMER_IRQ_0"]
    TIMER_IRQ_0 = 0,
    #[doc = "1 - TIMER_IRQ_1"]
    TIMER_IRQ_1 = 1,
    #[doc = "2 - TIMER_IRQ_2"]
    TIMER_IRQ_2 = 2,
    #[doc = "3 - TIMER_IRQ_3"]
    TIMER_IRQ_3 = 3,
    #[doc = "4 - PWM_IRQ_WRAP"]
    PWM_IRQ_WRAP = 4,
    #[doc = "5 - USBCTRL_IRQ"]
    USBCTRL_IRQ = 5,
    #[doc = "6 - XIP_IRQ"]
    XIP_IRQ = 6,
    #[doc = "7 - PIO0_IRQ_0"]
    PIO0_IRQ_0 = 7,
    #[doc = "8 - PIO0_IRQ_1"]
    PIO0_IRQ_1 = 8,
    #[doc = "9 - PIO1_IRQ_0"]
    PIO1_IRQ_0 = 9,
    #[doc = "10 - PIO1_IRQ_1"]
    PIO1_IRQ_1 = 10,
    #[doc = "11 - DMA_IRQ_0"]
    DMA_IRQ_0 = 11,
    #[doc = "12 - DMA_IRQ_1"]
    DMA_IRQ_1 = 12,
    #[doc = "13 - IO_IRQ_BANK0"]
    IO_IRQ_BANK0 = 13,
    #[doc = "14 - IO_IRQ_QSPI"]
    IO_IRQ_QSPI = 14,
    #[doc = "15 - SIO_IRQ_PROC0"]
    SIO_IRQ_PROC0 = 15,
    #[doc = "16 - SIO_IRQ_PROC1"]
    SIO_IRQ_PROC1 = 16,
    #[doc = "17 - CLOCKS_IRQ"]
    CLOCKS_IRQ = 17,
    #[doc = "18 - SPI0_IRQ"]
    SPI0_IRQ = 18,
    #[doc = "19 - SPI1_IRQ"]
    SPI1_IRQ = 19,
    #[doc = "20 - UART0_IRQ"]
    UART0_IRQ = 20,
    #[doc = "21 - UART1_IRQ"]
    UART1_IRQ = 21,
    #[doc = "22 - ADC_IRQ_FIFO"]
    ADC_IRQ_FIFO = 22,
    #[doc = "23 - I2C0_IRQ"]
    I2C0_IRQ = 23,
    #[doc = "24 - I2C1_IRQ"]
    I2C1_IRQ = 24,
    #[doc = "25 - RTC_IRQ"]
    RTC_IRQ = 25,
    #[doc = "26 - Software IRQ 0"]
    SW0_IRQ = 26,
    #[doc = "27 - Software IRQ 1"]
    SW1_IRQ = 27,
    #[doc = "28 - Software IRQ 2"]
    SW2_IRQ = 28,
    #[doc = "29 - Software IRQ 3"]
    SW3_IRQ = 29,
    #[doc = "30 - Software IRQ 4"]
    SW4_IRQ = 30,
    #[doc = "31 - Software IRQ 5"]
    SW5_IRQ = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "QSPI flash execute-in-place block"]
pub type XIP_CTRL = crate::Periph<xip_ctrl::RegisterBlock, 0x1400_0000>;
impl core::fmt::Debug for XIP_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XIP_CTRL").finish()
    }
}
#[doc = "QSPI flash execute-in-place block"]
pub mod xip_ctrl;
#[doc = "DW_apb_ssi has the following features:  
 * APB interface - Allows for easy integration into a DesignWare Synthesizable Components for AMBA 2 implementation.  
 * APB3 and APB4 protocol support.  
 * Scalable APB data bus width - Supports APB data bus widths of 8, 16, and 32 bits.  
 * Serial-master or serial-slave operation - Enables serial communication with serial-master or serial-slave peripheral devices.  
 * Programmable Dual/Quad/Octal SPI support in Master Mode.  
 * Dual Data Rate (DDR) and Read Data Strobe (RDS) Support - Enables the DW_apb_ssi master to perform operations with the device in DDR and RDS modes when working in Dual/Quad/Octal mode of operation.  
 * Data Mask Support - Enables the DW_apb_ssi to selectively update the bytes in the device. This feature is applicable only in enhanced SPI modes.  
 * eXecute-In-Place (XIP) support - Enables the DW_apb_ssi master to behave as a memory mapped I/O and fetches the data from the device based on the APB read request. This feature is applicable only in enhanced SPI modes.  
 * DMA Controller Interface - Enables the DW_apb_ssi to interface to a DMA controller over the bus using a handshaking interface for transfer requests.  
 * Independent masking of interrupts - Master collision, transmit FIFO overflow, transmit FIFO empty, receive FIFO full, receive FIFO underflow, and receive FIFO overflow interrupts can all be masked independently.  
 * Multi-master contention detection - Informs the processor of multiple serial-master accesses on the serial bus.  
 * Bypass of meta-stability flip-flops for synchronous clocks - When the APB clock (pclk) and the DW_apb_ssi serial clock (ssi_clk) are synchronous, meta-stable flip-flops are not used when transferring control signals across these clock domains.  
 * Programmable delay on the sample time of the received serial data bit (rxd); enables programmable control of routing delays resulting in higher serial data-bit rates.  
 * Programmable features:  
 - Serial interface operation - Choice of Motorola SPI, Texas Instruments Synchronous Serial Protocol or National Semiconductor Microwire.  
 - Clock bit-rate - Dynamic control of the serial bit rate of the data transfer; used in only serial-master mode of operation.  
 - Data Item size (4 to 32 bits) - Item size of each data transfer under the control of the programmer.  
 * Configured features:  
 - FIFO depth - 16 words deep. The FIFO width is fixed at 32 bits.  
 - 1 slave select output.  
 - Hardware slave-select - Dedicated hardware slave-select line.  
 - Combined interrupt line - one combined interrupt line from the DW_apb_ssi to the interrupt controller.  
 - Interrupt polarity - active high interrupt lines.  
 - Serial clock polarity - low serial-clock polarity directly after reset.  
 - Serial clock phase - capture on first edge of serial-clock directly after reset."]
pub type XIP_SSI = crate::Periph<xip_ssi::RegisterBlock, 0x1800_0000>;
impl core::fmt::Debug for XIP_SSI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XIP_SSI").finish()
    }
}
#[doc = "DW_apb_ssi has the following features:  
 * APB interface - Allows for easy integration into a DesignWare Synthesizable Components for AMBA 2 implementation.  
 * APB3 and APB4 protocol support.  
 * Scalable APB data bus width - Supports APB data bus widths of 8, 16, and 32 bits.  
 * Serial-master or serial-slave operation - Enables serial communication with serial-master or serial-slave peripheral devices.  
 * Programmable Dual/Quad/Octal SPI support in Master Mode.  
 * Dual Data Rate (DDR) and Read Data Strobe (RDS) Support - Enables the DW_apb_ssi master to perform operations with the device in DDR and RDS modes when working in Dual/Quad/Octal mode of operation.  
 * Data Mask Support - Enables the DW_apb_ssi to selectively update the bytes in the device. This feature is applicable only in enhanced SPI modes.  
 * eXecute-In-Place (XIP) support - Enables the DW_apb_ssi master to behave as a memory mapped I/O and fetches the data from the device based on the APB read request. This feature is applicable only in enhanced SPI modes.  
 * DMA Controller Interface - Enables the DW_apb_ssi to interface to a DMA controller over the bus using a handshaking interface for transfer requests.  
 * Independent masking of interrupts - Master collision, transmit FIFO overflow, transmit FIFO empty, receive FIFO full, receive FIFO underflow, and receive FIFO overflow interrupts can all be masked independently.  
 * Multi-master contention detection - Informs the processor of multiple serial-master accesses on the serial bus.  
 * Bypass of meta-stability flip-flops for synchronous clocks - When the APB clock (pclk) and the DW_apb_ssi serial clock (ssi_clk) are synchronous, meta-stable flip-flops are not used when transferring control signals across these clock domains.  
 * Programmable delay on the sample time of the received serial data bit (rxd); enables programmable control of routing delays resulting in higher serial data-bit rates.  
 * Programmable features:  
 - Serial interface operation - Choice of Motorola SPI, Texas Instruments Synchronous Serial Protocol or National Semiconductor Microwire.  
 - Clock bit-rate - Dynamic control of the serial bit rate of the data transfer; used in only serial-master mode of operation.  
 - Data Item size (4 to 32 bits) - Item size of each data transfer under the control of the programmer.  
 * Configured features:  
 - FIFO depth - 16 words deep. The FIFO width is fixed at 32 bits.  
 - 1 slave select output.  
 - Hardware slave-select - Dedicated hardware slave-select line.  
 - Combined interrupt line - one combined interrupt line from the DW_apb_ssi to the interrupt controller.  
 - Interrupt polarity - active high interrupt lines.  
 - Serial clock polarity - low serial-clock polarity directly after reset.  
 - Serial clock phase - capture on first edge of serial-clock directly after reset."]
pub mod xip_ssi;
#[doc = "SYSINFO"]
pub type SYSINFO = crate::Periph<sysinfo::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for SYSINFO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSINFO").finish()
    }
}
#[doc = "SYSINFO"]
pub mod sysinfo;
#[doc = "Register block for various chip control signals"]
pub type SYSCFG = crate::Periph<syscfg::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for SYSCFG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSCFG").finish()
    }
}
#[doc = "Register block for various chip control signals"]
pub mod syscfg;
#[doc = "CLOCKS"]
pub type CLOCKS = crate::Periph<clocks::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for CLOCKS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CLOCKS").finish()
    }
}
#[doc = "CLOCKS"]
pub mod clocks;
#[doc = "RESETS"]
pub type RESETS = crate::Periph<resets::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for RESETS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RESETS").finish()
    }
}
#[doc = "RESETS"]
pub mod resets;
#[doc = "PSM"]
pub type PSM = crate::Periph<psm::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for PSM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PSM").finish()
    }
}
#[doc = "PSM"]
pub mod psm;
#[doc = "IO_BANK0"]
pub type IO_BANK0 = crate::Periph<io_bank0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for IO_BANK0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IO_BANK0").finish()
    }
}
#[doc = "IO_BANK0"]
pub mod io_bank0;
#[doc = "IO_QSPI"]
pub type IO_QSPI = crate::Periph<io_qspi::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for IO_QSPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IO_QSPI").finish()
    }
}
#[doc = "IO_QSPI"]
pub mod io_qspi;
#[doc = "PADS_BANK0"]
pub type PADS_BANK0 = crate::Periph<pads_bank0::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for PADS_BANK0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PADS_BANK0").finish()
    }
}
#[doc = "PADS_BANK0"]
pub mod pads_bank0;
#[doc = "PADS_QSPI"]
pub type PADS_QSPI = crate::Periph<pads_qspi::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for PADS_QSPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PADS_QSPI").finish()
    }
}
#[doc = "PADS_QSPI"]
pub mod pads_qspi;
#[doc = "Controls the crystal oscillator"]
pub type XOSC = crate::Periph<xosc::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for XOSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XOSC").finish()
    }
}
#[doc = "Controls the crystal oscillator"]
pub mod xosc;
#[doc = "PLL_SYS"]
pub type PLL_SYS = crate::Periph<pll_sys::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for PLL_SYS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PLL_SYS").finish()
    }
}
#[doc = "PLL_SYS"]
pub mod pll_sys;
#[doc = "PLL_USB"]
pub type PLL_USB = crate::Periph<pll_sys::RegisterBlock, 0x4002_c000>;
impl core::fmt::Debug for PLL_USB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PLL_USB").finish()
    }
}
#[doc = "PLL_USB"]
pub use self::pll_sys as pll_usb;
#[doc = "Register block for busfabric control signals and performance counters"]
pub type BUSCTRL = crate::Periph<busctrl::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for BUSCTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BUSCTRL").finish()
    }
}
#[doc = "Register block for busfabric control signals and performance counters"]
pub mod busctrl;
#[doc = "UART0"]
pub type UART0 = crate::Periph<uart0::RegisterBlock, 0x4003_4000>;
impl core::fmt::Debug for UART0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART0").finish()
    }
}
#[doc = "UART0"]
pub mod uart0;
#[doc = "UART1"]
pub type UART1 = crate::Periph<uart0::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for UART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART1").finish()
    }
}
#[doc = "UART1"]
pub use self::uart0 as uart1;
#[doc = "SPI0"]
pub type SPI0 = crate::Periph<spi0::RegisterBlock, 0x4003_c000>;
impl core::fmt::Debug for SPI0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI0").finish()
    }
}
#[doc = "SPI0"]
pub mod spi0;
#[doc = "SPI1"]
pub type SPI1 = crate::Periph<spi0::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
#[doc = "SPI1"]
pub use self::spi0 as spi1;
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0  
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8  
 IC_UFM_SCL_LOW_COUNT .............. 0x0008  
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006  
 IC_TX_TL .......................... 0x0  
 IC_TX_CMD_BLOCK ................... 0x1  
 IC_HAS_DMA ........................ 0x1  
 IC_HAS_ASYNC_FIFO ................. 0x0  
 IC_SMBUS_ARP ...................... 0x0  
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1  
 IC_INTR_IO ........................ 0x1  
 IC_MASTER_MODE .................... 0x1  
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1  
 IC_INTR_POL ....................... 0x1  
 IC_OPTIONAL_SAR ................... 0x0  
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055  
 IC_DEFAULT_SLAVE_ADDR ............. 0x055  
 IC_DEFAULT_HS_SPKLEN .............. 0x1  
 IC_FS_SCL_HIGH_COUNT .............. 0x0006  
 IC_HS_SCL_LOW_COUNT ............... 0x0008  
 IC_DEVICE_ID_VALUE ................ 0x0  
 IC_10BITADDR_MASTER ............... 0x0  
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0  
 IC_DEFAULT_FS_SPKLEN .............. 0x7  
 IC_ADD_ENCODED_PARAMS ............. 0x0  
 IC_DEFAULT_SDA_HOLD ............... 0x000001  
 IC_DEFAULT_SDA_SETUP .............. 0x64  
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0  
 IC_CLOCK_PERIOD ................... 100  
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1  
 IC_RESTART_EN ..................... 0x1  
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0  
 IC_BUS_CLEAR_FEATURE .............. 0x0  
 IC_CAP_LOADING .................... 100  
 IC_FS_SCL_LOW_COUNT ............... 0x000d  
 APB_DATA_WIDTH .................... 32  
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_SLV_DATA_NACK_ONLY ............. 0x1  
 IC_10BITADDR_SLAVE ................ 0x0  
 IC_CLK_TYPE ....................... 0x0  
 IC_SMBUS_UDID_MSB ................. 0x0  
 IC_SMBUS_SUSPEND_ALERT ............ 0x0  
 IC_HS_SCL_HIGH_COUNT .............. 0x0006  
 IC_SLV_RESTART_DET_EN ............. 0x1  
 IC_SMBUS .......................... 0x0  
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0  
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0  
 IC_USE_COUNTS ..................... 0x0  
 IC_RX_BUFFER_DEPTH ................ 16  
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_RX_FULL_HLD_BUS_EN ............. 0x1  
 IC_SLAVE_DISABLE .................. 0x1  
 IC_RX_TL .......................... 0x0  
 IC_DEVICE_ID ...................... 0x0  
 IC_HC_COUNT_VALUES ................ 0x0  
 I2C_DYNAMIC_TAR_UPDATE ............ 0  
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff  
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff  
 IC_HS_MASTER_CODE ................. 0x1  
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff  
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff  
 IC_SS_SCL_HIGH_COUNT .............. 0x0028  
 IC_SS_SCL_LOW_COUNT ............... 0x002f  
 IC_MAX_SPEED_MODE ................. 0x2  
 IC_STAT_FOR_CLK_STRETCH ........... 0x0  
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0  
 IC_DEFAULT_UFM_SPKLEN ............. 0x1  
 IC_TX_BUFFER_DEPTH ................ 16"]
pub type I2C0 = crate::Periph<i2c0::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for I2C0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C0").finish()
    }
}
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0  
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8  
 IC_UFM_SCL_LOW_COUNT .............. 0x0008  
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006  
 IC_TX_TL .......................... 0x0  
 IC_TX_CMD_BLOCK ................... 0x1  
 IC_HAS_DMA ........................ 0x1  
 IC_HAS_ASYNC_FIFO ................. 0x0  
 IC_SMBUS_ARP ...................... 0x0  
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1  
 IC_INTR_IO ........................ 0x1  
 IC_MASTER_MODE .................... 0x1  
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1  
 IC_INTR_POL ....................... 0x1  
 IC_OPTIONAL_SAR ................... 0x0  
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055  
 IC_DEFAULT_SLAVE_ADDR ............. 0x055  
 IC_DEFAULT_HS_SPKLEN .............. 0x1  
 IC_FS_SCL_HIGH_COUNT .............. 0x0006  
 IC_HS_SCL_LOW_COUNT ............... 0x0008  
 IC_DEVICE_ID_VALUE ................ 0x0  
 IC_10BITADDR_MASTER ............... 0x0  
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0  
 IC_DEFAULT_FS_SPKLEN .............. 0x7  
 IC_ADD_ENCODED_PARAMS ............. 0x0  
 IC_DEFAULT_SDA_HOLD ............... 0x000001  
 IC_DEFAULT_SDA_SETUP .............. 0x64  
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0  
 IC_CLOCK_PERIOD ................... 100  
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1  
 IC_RESTART_EN ..................... 0x1  
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0  
 IC_BUS_CLEAR_FEATURE .............. 0x0  
 IC_CAP_LOADING .................... 100  
 IC_FS_SCL_LOW_COUNT ............... 0x000d  
 APB_DATA_WIDTH .................... 32  
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_SLV_DATA_NACK_ONLY ............. 0x1  
 IC_10BITADDR_SLAVE ................ 0x0  
 IC_CLK_TYPE ....................... 0x0  
 IC_SMBUS_UDID_MSB ................. 0x0  
 IC_SMBUS_SUSPEND_ALERT ............ 0x0  
 IC_HS_SCL_HIGH_COUNT .............. 0x0006  
 IC_SLV_RESTART_DET_EN ............. 0x1  
 IC_SMBUS .......................... 0x0  
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0  
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0  
 IC_USE_COUNTS ..................... 0x0  
 IC_RX_BUFFER_DEPTH ................ 16  
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_RX_FULL_HLD_BUS_EN ............. 0x1  
 IC_SLAVE_DISABLE .................. 0x1  
 IC_RX_TL .......................... 0x0  
 IC_DEVICE_ID ...................... 0x0  
 IC_HC_COUNT_VALUES ................ 0x0  
 I2C_DYNAMIC_TAR_UPDATE ............ 0  
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff  
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff  
 IC_HS_MASTER_CODE ................. 0x1  
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff  
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff  
 IC_SS_SCL_HIGH_COUNT .............. 0x0028  
 IC_SS_SCL_LOW_COUNT ............... 0x002f  
 IC_MAX_SPEED_MODE ................. 0x2  
 IC_STAT_FOR_CLK_STRETCH ........... 0x0  
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0  
 IC_DEFAULT_UFM_SPKLEN ............. 0x1  
 IC_TX_BUFFER_DEPTH ................ 16"]
pub mod i2c0;
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0  
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8  
 IC_UFM_SCL_LOW_COUNT .............. 0x0008  
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006  
 IC_TX_TL .......................... 0x0  
 IC_TX_CMD_BLOCK ................... 0x1  
 IC_HAS_DMA ........................ 0x1  
 IC_HAS_ASYNC_FIFO ................. 0x0  
 IC_SMBUS_ARP ...................... 0x0  
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1  
 IC_INTR_IO ........................ 0x1  
 IC_MASTER_MODE .................... 0x1  
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1  
 IC_INTR_POL ....................... 0x1  
 IC_OPTIONAL_SAR ................... 0x0  
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055  
 IC_DEFAULT_SLAVE_ADDR ............. 0x055  
 IC_DEFAULT_HS_SPKLEN .............. 0x1  
 IC_FS_SCL_HIGH_COUNT .............. 0x0006  
 IC_HS_SCL_LOW_COUNT ............... 0x0008  
 IC_DEVICE_ID_VALUE ................ 0x0  
 IC_10BITADDR_MASTER ............... 0x0  
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0  
 IC_DEFAULT_FS_SPKLEN .............. 0x7  
 IC_ADD_ENCODED_PARAMS ............. 0x0  
 IC_DEFAULT_SDA_HOLD ............... 0x000001  
 IC_DEFAULT_SDA_SETUP .............. 0x64  
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0  
 IC_CLOCK_PERIOD ................... 100  
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1  
 IC_RESTART_EN ..................... 0x1  
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0  
 IC_BUS_CLEAR_FEATURE .............. 0x0  
 IC_CAP_LOADING .................... 100  
 IC_FS_SCL_LOW_COUNT ............... 0x000d  
 APB_DATA_WIDTH .................... 32  
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_SLV_DATA_NACK_ONLY ............. 0x1  
 IC_10BITADDR_SLAVE ................ 0x0  
 IC_CLK_TYPE ....................... 0x0  
 IC_SMBUS_UDID_MSB ................. 0x0  
 IC_SMBUS_SUSPEND_ALERT ............ 0x0  
 IC_HS_SCL_HIGH_COUNT .............. 0x0006  
 IC_SLV_RESTART_DET_EN ............. 0x1  
 IC_SMBUS .......................... 0x0  
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0  
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0  
 IC_USE_COUNTS ..................... 0x0  
 IC_RX_BUFFER_DEPTH ................ 16  
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_RX_FULL_HLD_BUS_EN ............. 0x1  
 IC_SLAVE_DISABLE .................. 0x1  
 IC_RX_TL .......................... 0x0  
 IC_DEVICE_ID ...................... 0x0  
 IC_HC_COUNT_VALUES ................ 0x0  
 I2C_DYNAMIC_TAR_UPDATE ............ 0  
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff  
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff  
 IC_HS_MASTER_CODE ................. 0x1  
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff  
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff  
 IC_SS_SCL_HIGH_COUNT .............. 0x0028  
 IC_SS_SCL_LOW_COUNT ............... 0x002f  
 IC_MAX_SPEED_MODE ................. 0x2  
 IC_STAT_FOR_CLK_STRETCH ........... 0x0  
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0  
 IC_DEFAULT_UFM_SPKLEN ............. 0x1  
 IC_TX_BUFFER_DEPTH ................ 16"]
pub type I2C1 = crate::Periph<i2c0::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "DW_apb_i2c address block  

 List of configuration constants for the Synopsys I2C hardware (you may see references to these in I2C register header; these are *fixed* values, set at hardware design time):  

 IC_ULTRA_FAST_MODE ................ 0x0  
 IC_UFM_TBUF_CNT_DEFAULT ........... 0x8  
 IC_UFM_SCL_LOW_COUNT .............. 0x0008  
 IC_UFM_SCL_HIGH_COUNT ............. 0x0006  
 IC_TX_TL .......................... 0x0  
 IC_TX_CMD_BLOCK ................... 0x1  
 IC_HAS_DMA ........................ 0x1  
 IC_HAS_ASYNC_FIFO ................. 0x0  
 IC_SMBUS_ARP ...................... 0x0  
 IC_FIRST_DATA_BYTE_STATUS ......... 0x1  
 IC_INTR_IO ........................ 0x1  
 IC_MASTER_MODE .................... 0x1  
 IC_DEFAULT_ACK_GENERAL_CALL ....... 0x1  
 IC_INTR_POL ....................... 0x1  
 IC_OPTIONAL_SAR ................... 0x0  
 IC_DEFAULT_TAR_SLAVE_ADDR ......... 0x055  
 IC_DEFAULT_SLAVE_ADDR ............. 0x055  
 IC_DEFAULT_HS_SPKLEN .............. 0x1  
 IC_FS_SCL_HIGH_COUNT .............. 0x0006  
 IC_HS_SCL_LOW_COUNT ............... 0x0008  
 IC_DEVICE_ID_VALUE ................ 0x0  
 IC_10BITADDR_MASTER ............... 0x0  
 IC_CLK_FREQ_OPTIMIZATION .......... 0x0  
 IC_DEFAULT_FS_SPKLEN .............. 0x7  
 IC_ADD_ENCODED_PARAMS ............. 0x0  
 IC_DEFAULT_SDA_HOLD ............... 0x000001  
 IC_DEFAULT_SDA_SETUP .............. 0x64  
 IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT . 0x0  
 IC_CLOCK_PERIOD ................... 100  
 IC_EMPTYFIFO_HOLD_MASTER_EN ....... 1  
 IC_RESTART_EN ..................... 0x1  
 IC_TX_CMD_BLOCK_DEFAULT ........... 0x0  
 IC_BUS_CLEAR_FEATURE .............. 0x0  
 IC_CAP_LOADING .................... 100  
 IC_FS_SCL_LOW_COUNT ............... 0x000d  
 APB_DATA_WIDTH .................... 32  
 IC_SDA_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_SLV_DATA_NACK_ONLY ............. 0x1  
 IC_10BITADDR_SLAVE ................ 0x0  
 IC_CLK_TYPE ....................... 0x0  
 IC_SMBUS_UDID_MSB ................. 0x0  
 IC_SMBUS_SUSPEND_ALERT ............ 0x0  
 IC_HS_SCL_HIGH_COUNT .............. 0x0006  
 IC_SLV_RESTART_DET_EN ............. 0x1  
 IC_SMBUS .......................... 0x0  
 IC_OPTIONAL_SAR_DEFAULT ........... 0x0  
 IC_PERSISTANT_SLV_ADDR_DEFAULT .... 0x0  
 IC_USE_COUNTS ..................... 0x0  
 IC_RX_BUFFER_DEPTH ................ 16  
 IC_SCL_STUCK_TIMEOUT_DEFAULT ...... 0xffffffff  
 IC_RX_FULL_HLD_BUS_EN ............. 0x1  
 IC_SLAVE_DISABLE .................. 0x1  
 IC_RX_TL .......................... 0x0  
 IC_DEVICE_ID ...................... 0x0  
 IC_HC_COUNT_VALUES ................ 0x0  
 I2C_DYNAMIC_TAR_UPDATE ............ 0  
 IC_SMBUS_CLK_LOW_MEXT_DEFAULT ..... 0xffffffff  
 IC_SMBUS_CLK_LOW_SEXT_DEFAULT ..... 0xffffffff  
 IC_HS_MASTER_CODE ................. 0x1  
 IC_SMBUS_RST_IDLE_CNT_DEFAULT ..... 0xffff  
 IC_SMBUS_UDID_LSB_DEFAULT ......... 0xffffffff  
 IC_SS_SCL_HIGH_COUNT .............. 0x0028  
 IC_SS_SCL_LOW_COUNT ............... 0x002f  
 IC_MAX_SPEED_MODE ................. 0x2  
 IC_STAT_FOR_CLK_STRETCH ........... 0x0  
 IC_STOP_DET_IF_MASTER_ACTIVE ...... 0x0  
 IC_DEFAULT_UFM_SPKLEN ............. 0x1  
 IC_TX_BUFFER_DEPTH ................ 16"]
pub use self::i2c0 as i2c1;
#[doc = "Control and data interface to SAR ADC"]
pub type ADC = crate::Periph<adc::RegisterBlock, 0x4004_c000>;
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
#[doc = "Control and data interface to SAR ADC"]
pub mod adc;
#[doc = "Simple PWM"]
pub type PWM = crate::Periph<pwm::RegisterBlock, 0x4005_0000>;
impl core::fmt::Debug for PWM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWM").finish()
    }
}
#[doc = "Simple PWM"]
pub mod pwm;
#[doc = "Controls time and alarms  
 time is a 64 bit value indicating the time in usec since power-on  
 timeh is the top 32 bits of time & timel is the bottom 32 bits  
 to change time write to timelw before timehw  
 to read time read from timelr before timehr  
 An alarm is set by setting alarm_enable and writing to the corresponding alarm register  
 When an alarm is pending, the corresponding alarm_running signal will be high  
 An alarm can be cancelled before it has finished by clearing the alarm_enable  
 When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared  
 To clear the interrupt write a 1 to the corresponding alarm_irq"]
pub type TIMER = crate::Periph<timer::RegisterBlock, 0x4005_4000>;
impl core::fmt::Debug for TIMER {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER").finish()
    }
}
#[doc = "Controls time and alarms  
 time is a 64 bit value indicating the time in usec since power-on  
 timeh is the top 32 bits of time & timel is the bottom 32 bits  
 to change time write to timelw before timehw  
 to read time read from timelr before timehr  
 An alarm is set by setting alarm_enable and writing to the corresponding alarm register  
 When an alarm is pending, the corresponding alarm_running signal will be high  
 An alarm can be cancelled before it has finished by clearing the alarm_enable  
 When an alarm fires, the corresponding alarm_irq is set and alarm_running is cleared  
 To clear the interrupt write a 1 to the corresponding alarm_irq"]
pub mod timer;
#[doc = "WATCHDOG"]
pub type WATCHDOG = crate::Periph<watchdog::RegisterBlock, 0x4005_8000>;
impl core::fmt::Debug for WATCHDOG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WATCHDOG").finish()
    }
}
#[doc = "WATCHDOG"]
pub mod watchdog;
#[doc = "Register block to control RTC"]
pub type RTC = crate::Periph<rtc::RegisterBlock, 0x4005_c000>;
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
#[doc = "Register block to control RTC"]
pub mod rtc;
#[doc = "ROSC"]
pub type ROSC = crate::Periph<rosc::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for ROSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ROSC").finish()
    }
}
#[doc = "ROSC"]
pub mod rosc;
#[doc = "control and status for on-chip voltage regulator and chip level reset subsystem"]
pub type VREG_AND_CHIP_RESET = crate::Periph<vreg_and_chip_reset::RegisterBlock, 0x4006_4000>;
impl core::fmt::Debug for VREG_AND_CHIP_RESET {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VREG_AND_CHIP_RESET").finish()
    }
}
#[doc = "control and status for on-chip voltage regulator and chip level reset subsystem"]
pub mod vreg_and_chip_reset;
#[doc = "Testbench manager. Allows the programmer to know what platform their software is running on."]
pub type TBMAN = crate::Periph<tbman::RegisterBlock, 0x4006_c000>;
impl core::fmt::Debug for TBMAN {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TBMAN").finish()
    }
}
#[doc = "Testbench manager. Allows the programmer to know what platform their software is running on."]
pub mod tbman;
#[doc = "DMA with separate read and write masters"]
pub type DMA = crate::Periph<dma::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for DMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA").finish()
    }
}
#[doc = "DMA with separate read and write masters"]
pub mod dma;
#[doc = "DPRAM layout for USB device."]
pub type USBCTRL_DPRAM = crate::Periph<usbctrl_dpram::RegisterBlock, 0x5010_0000>;
impl core::fmt::Debug for USBCTRL_DPRAM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USBCTRL_DPRAM").finish()
    }
}
#[doc = "DPRAM layout for USB device."]
pub mod usbctrl_dpram;
#[doc = "USB FS/LS controller device registers"]
pub type USBCTRL_REGS = crate::Periph<usbctrl_regs::RegisterBlock, 0x5011_0000>;
impl core::fmt::Debug for USBCTRL_REGS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USBCTRL_REGS").finish()
    }
}
#[doc = "USB FS/LS controller device registers"]
pub mod usbctrl_regs;
#[doc = "Programmable IO block"]
pub type PIO0 = crate::Periph<pio0::RegisterBlock, 0x5020_0000>;
impl core::fmt::Debug for PIO0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIO0").finish()
    }
}
#[doc = "Programmable IO block"]
pub mod pio0;
#[doc = "Programmable IO block"]
pub type PIO1 = crate::Periph<pio0::RegisterBlock, 0x5030_0000>;
impl core::fmt::Debug for PIO1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIO1").finish()
    }
}
#[doc = "Programmable IO block"]
pub use self::pio0 as pio1;
#[doc = "Single-cycle IO block  
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub type SIO = crate::Periph<sio::RegisterBlock, 0xd000_0000>;
impl core::fmt::Debug for SIO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SIO").finish()
    }
}
#[doc = "Single-cycle IO block  
 Provides core-local and inter-core hardware for the two processors, with single-cycle access."]
pub mod sio;
#[doc = "PPB"]
pub type PPB = crate::Periph<ppb::RegisterBlock, 0xe000_0000>;
impl core::fmt::Debug for PPB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PPB").finish()
    }
}
#[doc = "PPB"]
pub mod ppb;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub ADC: ADC,
    #[doc = "BUSCTRL"]
    pub BUSCTRL: BUSCTRL,
    #[doc = "CLOCKS"]
    pub CLOCKS: CLOCKS,
    #[doc = "DMA"]
    pub DMA: DMA,
    #[doc = "I2C0"]
    pub I2C0: I2C0,
    #[doc = "I2C1"]
    pub I2C1: I2C1,
    #[doc = "IO_BANK0"]
    pub IO_BANK0: IO_BANK0,
    #[doc = "IO_QSPI"]
    pub IO_QSPI: IO_QSPI,
    #[doc = "PADS_BANK0"]
    pub PADS_BANK0: PADS_BANK0,
    #[doc = "PADS_QSPI"]
    pub PADS_QSPI: PADS_QSPI,
    #[doc = "PIO0"]
    pub PIO0: PIO0,
    #[doc = "PIO1"]
    pub PIO1: PIO1,
    #[doc = "PLL_SYS"]
    pub PLL_SYS: PLL_SYS,
    #[doc = "PLL_USB"]
    pub PLL_USB: PLL_USB,
    #[doc = "PPB"]
    pub PPB: PPB,
    #[doc = "PSM"]
    pub PSM: PSM,
    #[doc = "PWM"]
    pub PWM: PWM,
    #[doc = "RESETS"]
    pub RESETS: RESETS,
    #[doc = "ROSC"]
    pub ROSC: ROSC,
    #[doc = "RTC"]
    pub RTC: RTC,
    #[doc = "SIO"]
    pub SIO: SIO,
    #[doc = "SPI0"]
    pub SPI0: SPI0,
    #[doc = "SPI1"]
    pub SPI1: SPI1,
    #[doc = "SYSCFG"]
    pub SYSCFG: SYSCFG,
    #[doc = "SYSINFO"]
    pub SYSINFO: SYSINFO,
    #[doc = "TBMAN"]
    pub TBMAN: TBMAN,
    #[doc = "TIMER"]
    pub TIMER: TIMER,
    #[doc = "UART0"]
    pub UART0: UART0,
    #[doc = "UART1"]
    pub UART1: UART1,
    #[doc = "USBCTRL_DPRAM"]
    pub USBCTRL_DPRAM: USBCTRL_DPRAM,
    #[doc = "USBCTRL_REGS"]
    pub USBCTRL_REGS: USBCTRL_REGS,
    #[doc = "VREG_AND_CHIP_RESET"]
    pub VREG_AND_CHIP_RESET: VREG_AND_CHIP_RESET,
    #[doc = "WATCHDOG"]
    pub WATCHDOG: WATCHDOG,
    #[doc = "XIP_CTRL"]
    pub XIP_CTRL: XIP_CTRL,
    #[doc = "XIP_SSI"]
    pub XIP_SSI: XIP_SSI,
    #[doc = "XOSC"]
    pub XOSC: XOSC,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            XIP_CTRL: XIP_CTRL::steal(),
            XIP_SSI: XIP_SSI::steal(),
            SYSINFO: SYSINFO::steal(),
            SYSCFG: SYSCFG::steal(),
            CLOCKS: CLOCKS::steal(),
            RESETS: RESETS::steal(),
            PSM: PSM::steal(),
            IO_BANK0: IO_BANK0::steal(),
            IO_QSPI: IO_QSPI::steal(),
            PADS_BANK0: PADS_BANK0::steal(),
            PADS_QSPI: PADS_QSPI::steal(),
            XOSC: XOSC::steal(),
            PLL_SYS: PLL_SYS::steal(),
            PLL_USB: PLL_USB::steal(),
            BUSCTRL: BUSCTRL::steal(),
            UART0: UART0::steal(),
            UART1: UART1::steal(),
            SPI0: SPI0::steal(),
            SPI1: SPI1::steal(),
            I2C0: I2C0::steal(),
            I2C1: I2C1::steal(),
            ADC: ADC::steal(),
            PWM: PWM::steal(),
            TIMER: TIMER::steal(),
            WATCHDOG: WATCHDOG::steal(),
            RTC: RTC::steal(),
            ROSC: ROSC::steal(),
            VREG_AND_CHIP_RESET: VREG_AND_CHIP_RESET::steal(),
            TBMAN: TBMAN::steal(),
            DMA: DMA::steal(),
            USBCTRL_DPRAM: USBCTRL_DPRAM::steal(),
            USBCTRL_REGS: USBCTRL_REGS::steal(),
            PIO0: PIO0::steal(),
            PIO1: PIO1::steal(),
            SIO: SIO::steal(),
            PPB: PPB::steal(),
        }
    }
}
