on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-24.11
    env:
      RUSTFLAGS: "-D warnings -A clippy::empty_docs -A non_camel_case_types"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
          components: clippy
      - run: cargo clippy
